print("Loading household_power_consumption.txt data file.")
data <- read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings = "?", colClasses = c('character','character','numeric','numeric','numeric','numeric','numeric','numeric','numeric'))
data$Date <- as.Date(data$Date, "%d/%m/%Y")
print("Filtering data.")
rm(smalldata)
smalldata <- subset(data,Date >= as.Date("2007-2-1") & Date <= as.Date("2007-2-2"))
rm(data)
smalldata$DateTime<-paste(smalldata$Date, smalldata$Time)
smalldata$DateTime<-strptime(smalldata$DateTime, "%Y-%m-%d %H:%M:%S")
print("smalldate table created.")
print("Now you can run scripts to produce graphics files.")
